import {API_ENDPOINT} from "@/utils/config";

export default {
    contactCoach(context, payload){
        const newRequest = {
            userEmail: payload.email,
            message: payload.message
        };
        fetch(`${API_ENDPOINT}/requests/${payload.coachId}.json`, {
            method: 'POST',
            body: JSON.stringify(newRequest)
        })
            .then(res => {
                if(!res.ok){
                    throw new Error('');
                }
                return res.json();
            })
            .then((res) => {
                // name: auto generated by Firebase
                newRequest.id = res.name;
                newRequest.coachId = payload.coachId;
            });
        context.commit('addRequest', newRequest);
    },
    fetchRequests(context){
        const coachId = context.rootGetters.userId;
        fetch(`${API_ENDPOINT}/requests/${coachId}`)
            .then(res => {
                if(!res.ok){
                    throw new Error('can not get');
                }
                return res.json();
            })
            .then(responseData => {
                const requests = [];

                for(const key in responseData){
                    const request = {
                        id: key,
                        coachId: coachId,
                        userEmail: responseData[key].userEmail,
                        message: responseData[key].message,
                    };
                    requests.push(request);
                }
                context.commit('setRequests', requests);
            });
    }
};